### ISSUE TITLE
dash in url leads to 404

### ISSUE THREAD

**Issue by DerZyklop** [td00/jitsi.rocks#1]
not sure if this is a jitsi or jitsi.rocks issue. 

A project name like Foo-Bar leads to a 404:
https://de-nue-1.jitsi.rocks/Foo-Bar

FooBar would work:
https://de-nue-1.jitsi.rocks/FooBar

**Comment by thies23** [comment]
It's a known bug in docker-jitsi upstream.
Will take a look when migrating from vanilla jitsi to customized jitsi.

**Comment by thies23** [comment]
fixed. :)
(https://de-fsn-1.jitsi.rocks/test-dash for reference ;) )

**Comment by DerZyklop** [comment]
🎉
